language: scala
before_install:
  - jdk_switcher use oraclejdk8
  - curl https://nixos.org/nix/install | sh
  - . /home/travis/.nix-profile/etc/profile.d/nix.sh
  - nix-env -i nix-prefetch-scripts
sudo: required
script:
  - pushd plugin
  - sbt scripted
  - popd
  - nix-env -i -f .
  - tests/multi-build/run.sh
  - tests/template-generation/run.sh
